import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:roamly/core/services/trip_service.dart';
import 'package:roamly/models/trip_model.dart';
import 'package:roamly/features/trips/screens/trip_details_screen.dart'; // We will create this
import 'package:firebase_auth/firebase_auth.dart';

// ── Main Screen ─────────────────────────────────────────────────────────

/// My Trips screen that manages a list of trips using TripService
class MyTripsScreen extends StatefulWidget {
  const MyTripsScreen({super.key});

  @override
  State<MyTripsScreen> createState() => _MyTripsScreenState();
}

class _MyTripsScreenState extends State<MyTripsScreen> {
  final TripService _tripService = TripService();
  final String _currentUserId = FirebaseAuth.instance.currentUser?.uid ?? '';

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<TripModel>>(
      stream: _tripService.getUserTrips(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        if (snapshot.hasError) {
          return Scaffold(
            body: Center(child: Text('Error loading trips: ${snapshot.error}')),
          );
        }

        final trips = snapshot.data ?? [];
        final activeTrips = trips.where((t) => 
            t.ownerId == _currentUserId || 
            t.companionIds.contains(_currentUserId) || 
            t.editorIds.contains(_currentUserId)).toList();
        final invitedTrips = trips.where((t) => 
            t.pendingCompanionIds.contains(_currentUserId) || 
            t.pendingEditorIds.contains(_currentUserId)).toList();

        return DefaultTabController(
          length: 2,
          child: Scaffold(
            appBar: AppBar(
              title: Text('My Trips', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
              elevation: 0,
              bottom: const TabBar(
                tabs: [
                  Tab(text: 'My Trips'),
                  Tab(text: 'Invitations'),
                ],
              ),
              actions: [
                Padding(
                  padding: const EdgeInsets.only(right: 16, top: 8, bottom: 8),
                  child: FilledButton.icon(
                    onPressed: _createNewTrip,
                    style: FilledButton.styleFrom(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
                    icon: const Icon(Icons.add, size: 18),
                    label: Text('New Trip', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
                  ),
                ),
              ],
            ),
            body: TabBarView(
              children: [
                _buildTripsList(activeTrips),
                _buildInvitationsList(invitedTrips),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildTripsList(List<TripModel> activeTrips) {
    return _TripsListView(
      trips: activeTrips,
      onCreateTrip: _createNewTrip,
      onViewTrip: (trip) {
         Navigator.push(
           context,
           MaterialPageRoute(
             builder: (context) => TripDetailsScreen(tripId: trip.id),
           ),
         );
      },
      onEditTrip: _editTrip,
      onDeleteTrip: _deleteTrip,
      currentUserId: _currentUserId,
    );
  }

  Widget _buildInvitationsList(List<TripModel> invitedTrips) {
    return _InvitationsListView(
      trips: invitedTrips,
      onAccept: (trip) async {
         await _tripService.acceptTripInvitation(trip);
      },
      onDecline: (trip) async {
         await _tripService.declineTripInvitation(trip);
      },
    );
  }

  void _createNewTrip() {
    _showTripFormModal(context, null).then((newTripData) async {
      if (newTripData != null && _currentUserId.isNotEmpty) {
         final trip = TripModel(
           id: '', // Generated by Firestore
           ownerId: _currentUserId,
           title: newTripData['title'],
           destination: newTripData['destination'],
           description: newTripData['description'],
           startDate: newTripData['startDate'],
           endDate: newTripData['endDate'],
           createdAt: DateTime.now(),
           updatedAt: DateTime.now(),
           locations: [],
         );
         await _tripService.createTrip(trip);
      }
    });
  }

  void _editTrip(TripModel trip) {
    if (trip.ownerId != _currentUserId && !trip.editorIds.contains(_currentUserId)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You do not have permission to edit this trip')),
      );
      return;
    }
    
    _showTripFormModal(context, trip).then((updatedData) async {
      if (updatedData != null) {
        final updatedTrip = trip.copyWith(
           title: updatedData['title'],
           destination: updatedData['destination'],
           description: updatedData['description'],
           startDate: updatedData['startDate'],
           endDate: updatedData['endDate'],
           updatedAt: DateTime.now(),
        );
        await _tripService.updateTrip(updatedTrip);
      }
    });
  }

  void _deleteTrip(TripModel trip) {
    if (trip.ownerId != _currentUserId) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Only the trip owner can delete the trip')),
      );
      return;
    }

    showDialog(
      context: context,
      builder: (ctx) {
        final isDark = Theme.of(context).brightness == Brightness.dark;
        return AlertDialog(
          backgroundColor: isDark ? const Color(0xFF16213E) : Colors.white,
          title: Text('Delete Trip?', style: GoogleFonts.poppins(color: Colors.red)),
          content: Text('Are you sure you want to delete "${trip.title}"?', 
            style: GoogleFonts.poppins(color: isDark ? Colors.white : Colors.black87)),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: Text('Cancel', style: GoogleFonts.poppins(color: isDark ? Colors.white70 : Colors.black87)),
            ),
            FilledButton(
              style: FilledButton.styleFrom(backgroundColor: Colors.red),
              onPressed: () async {
                Navigator.pop(ctx);
                await _tripService.deleteTrip(trip.id);
              },
              child: Text('Delete', style: GoogleFonts.poppins()),
            ),
          ],
        );
      },
    );
  }

  Future<Map<String, dynamic>?> _showTripFormModal(BuildContext context, TripModel? existingTrip) {
    return showModalBottomSheet<Map<String, dynamic>>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => _TripFormSheet(
        existingTrip: existingTrip,
        onSave: (title, dest, start, end, description) {
          return {
            'title': title,
            'destination': dest,
            'startDate': start,
            'endDate': end,
            'description': description,
          };
        },
      ),
    );
  }
}


// ── Trips List View ─────────────────────────────────────────────────────

// ignore: must_be_immutable
class _TripsListView extends StatelessWidget {
  final List<TripModel> trips;
  final VoidCallback onCreateTrip;
  final Function(TripModel) onViewTrip;
  final Function(TripModel) onEditTrip;
  final Function(TripModel) onDeleteTrip;
  final String currentUserId;

  _TripsListView({
    required this.trips,
    required this.onCreateTrip,
    required this.onViewTrip,
    required this.onEditTrip,
    required this.onDeleteTrip,
    required this.currentUserId,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primary = Theme.of(context).colorScheme.primary;
    final bgColor = isDark ? const Color(0xFF1A1A2E) : const Color(0xFFF4F6FB);

    return Scaffold(
      backgroundColor: bgColor,
      body: trips.isEmpty
          ? _buildEmptyState(isDark)
          : ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: trips.length,
              itemBuilder: (ctx, i) => _TripCard(
                trip: trips[i],
                isDark: isDark,
                primary: primary,
                onView: () => onViewTrip(trips[i]),
                onEdit: () => onEditTrip(trips[i]),
                onDelete: () => onDeleteTrip(trips[i]),
                currentUserId: currentUserId,
              ),
            ),
    );
  }

  Widget _buildEmptyState(bool isDark) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.flight_takeoff_rounded, size: 80, color: isDark ? Colors.white24 : Colors.grey[300]),
            const SizedBox(height: 24),
            Text(
              'No trips yet',
              style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.bold, color: isDark ? Colors.white : Colors.black87),
            ),
            const SizedBox(height: 12),
            Text(
              'You have no trips yet. Start planning your next adventure!',
              textAlign: TextAlign.center,
              style: GoogleFonts.poppins(fontSize: 14, color: isDark ? Colors.white54 : Colors.grey[600]),
            ),
            const SizedBox(height: 32),
            SizedBox(
              height: 50,
              width: 200,
              child: FilledButton(
                onPressed: onCreateTrip,
                style: FilledButton.styleFrom(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))),
                child: Text('Create New Trip', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _InvitationsListView extends StatelessWidget {
  final List<TripModel> trips;
  final Function(TripModel) onAccept;
  final Function(TripModel) onDecline;

  const _InvitationsListView({
    required this.trips,
    required this.onAccept,
    required this.onDecline,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final bgColor = isDark ? const Color(0xFF1A1A2E) : const Color(0xFFF4F6FB);

    if (trips.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
             Icon(Icons.mail_outline, size: 80, color: isDark ? Colors.white24 : Colors.grey[300]),
             const SizedBox(height: 24),
             Text(
               'No invitations',
               style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.bold, color: isDark ? Colors.white : Colors.black87),
             ),
             const SizedBox(height: 12),
             Text(
               'You have no pending trip invitations.',
               textAlign: TextAlign.center,
               style: GoogleFonts.poppins(fontSize: 14, color: isDark ? Colors.white54 : Colors.grey[600]),
             ),
          ],
        ),
      );
    }

    return Container(
      color: bgColor,
      child: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: trips.length,
        itemBuilder: (ctx, i) {
          final trip = trips[i];
          final dateFormat = DateFormat('MMM d, yyyy');
          final dateString = '${dateFormat.format(trip.startDate)}${trip.endDate != null ? ' - ${dateFormat.format(trip.endDate!)}' : ''}';
          
          return Container(
            margin: const EdgeInsets.only(bottom: 16),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF16213E) : Colors.white,
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: isDark ? Colors.grey[800]! : Colors.grey[200]!),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  trip.title,
                  style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold, color: isDark ? Colors.white : Colors.black87),
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Icon(Icons.location_on_outlined, size: 16, color: isDark ? Colors.white54 : Colors.grey[500]),
                    const SizedBox(width: 6),
                    Text(trip.destination ?? 'No destination set', style: GoogleFonts.poppins(fontSize: 14, color: isDark ? Colors.white70 : Colors.grey[700])),
                  ],
                ),
                const SizedBox(height: 4),
                Row(
                  children: [
                    Icon(Icons.calendar_month_outlined, size: 16, color: isDark ? Colors.white54 : Colors.grey[500]),
                    const SizedBox(width: 6),
                    Text(dateString, style: GoogleFonts.poppins(fontSize: 13, color: isDark ? Colors.white54 : Colors.grey[600])),
                  ],
                ),
                const SizedBox(height: 16),
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: () => onDecline(trip),
                        style: OutlinedButton.styleFrom(
                           foregroundColor: Colors.red,
                           side: const BorderSide(color: Colors.red),
                        ),
                        child: Text('Decline', style: GoogleFonts.poppins()),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: FilledButton(
                        onPressed: () => onAccept(trip),
                        child: Text('Accept', style: GoogleFonts.poppins()),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}

// ignore: must_be_immutable
class _TripCard extends StatelessWidget {
  final TripModel trip;
  final bool isDark;
  final Color primary;
  final VoidCallback onView;
  final VoidCallback onEdit;
  final VoidCallback onDelete;
  final String currentUserId;

  _TripCard({
    required this.trip,
    required this.isDark,
    required this.primary,
    required this.onView,
    required this.onEdit,
    required this.onDelete,
    required this.currentUserId,
  });

  @override
  Widget build(BuildContext context) {
    final dateFormat = DateFormat('MMM d, yyyy');
    final dateString = '${dateFormat.format(trip.startDate)}${trip.endDate != null ? ' - ${dateFormat.format(trip.endDate!)}' : ''}';
    final canEdit = trip.ownerId == currentUserId || trip.editorIds.contains(currentUserId);
    final isOwner = trip.ownerId == currentUserId;

    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF16213E) : Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: isDark ? Colors.grey[800]! : Colors.grey[200]!),
        boxShadow: isDark ? [] : [BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 12, offset: const Offset(0, 4))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(
                      child: Text(
                        trip.title,
                        style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold, color: isDark ? Colors.white : Colors.black87),
                      ),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      decoration: BoxDecoration(color: primary.withValues(alpha: 0.15), borderRadius: BorderRadius.circular(12)),
                      child: Text('${trip.locations.length} places', style: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w600, color: primary)),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Icon(Icons.location_on_outlined, size: 16, color: isDark ? Colors.white54 : Colors.grey[500]),
                    const SizedBox(width: 6),
                    Text(trip.destination ?? 'No destination set', style: GoogleFonts.poppins(fontSize: 14, color: isDark ? Colors.white70 : Colors.grey[700])),
                  ],
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Icon(Icons.calendar_month_outlined, size: 16, color: isDark ? Colors.white54 : Colors.grey[500]),
                    const SizedBox(width: 6),
                    Text(dateString, style: GoogleFonts.poppins(fontSize: 13, color: isDark ? Colors.white54 : Colors.grey[600])),
                  ],
                ),
              ],
            ),
          ),
          Divider(height: 1, color: isDark ? Colors.grey[800] : Colors.grey[200]),
          Row(
            children: [
              Expanded(
                child: TextButton.icon(
                  onPressed: onView,
                  icon: const Icon(Icons.remove_red_eye_outlined, size: 18),
                  label: const Text('View'),
                  style: TextButton.styleFrom(foregroundColor: primary, padding: const EdgeInsets.symmetric(vertical: 12)),
                ),
              ),
              if (canEdit)
                Container(width: 1, height: 24, color: isDark ? Colors.grey[800] : Colors.grey[200]),
              if (canEdit)
                Expanded(
                  child: TextButton.icon(
                    onPressed: onEdit,
                    icon: const Icon(Icons.edit_outlined, size: 18),
                    label: const Text('Edit'),
                    style: TextButton.styleFrom(foregroundColor: isDark ? Colors.white70 : Colors.grey[700], padding: const EdgeInsets.symmetric(vertical: 12)),
                  ),
                ),
              if (isOwner)
                Container(width: 1, height: 24, color: isDark ? Colors.grey[800] : Colors.grey[200]),
              if (isOwner)
                Expanded(
                  child: TextButton.icon(
                    onPressed: onDelete,
                    icon: const Icon(Icons.delete_outline, size: 18),
                    label: const Text('Delete'),
                    style: TextButton.styleFrom(foregroundColor: Colors.red, padding: const EdgeInsets.symmetric(vertical: 12)),
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }
}

// ── Shared Widgets ──────────────────────────────────────────────────────

// _SectionCard removed

// ── Create/Edit Form Bottom Sheet ───────────────────────────────────────

// ignore: must_be_immutable
class _TripFormSheet extends StatefulWidget {
  final TripModel? existingTrip;
  final Map<String, dynamic> Function(String title, String dest, DateTime start, DateTime end, String description) onSave;

  _TripFormSheet({this.existingTrip, required this.onSave});

  @override
  State<_TripFormSheet> createState() => _TripFormSheetState();
}

class _TripFormSheetState extends State<_TripFormSheet> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _titleCtrl;
  late TextEditingController _destCtrl;
  late TextEditingController _descCtrl;
  DateTime? _startDate;
  DateTime? _endDate;

  @override
  void initState() {
    super.initState();
    _titleCtrl = TextEditingController(text: widget.existingTrip?.title ?? '');
    _destCtrl = TextEditingController(text: widget.existingTrip?.destination ?? '');
    _descCtrl = TextEditingController(text: widget.existingTrip?.description ?? '');
    _startDate = widget.existingTrip?.startDate;
    _endDate = widget.existingTrip?.endDate ?? widget.existingTrip?.startDate;
  }

  Future<void> _pickDateRange() async {
    final range = await showDateRangePicker(
      context: context,
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now().add(const Duration(days: 365 * 5)),
      initialDateRange: _startDate != null && _endDate != null
          ? DateTimeRange(start: _startDate!, end: _endDate!)
          : null,
      builder: (ctx, child) {
        final isDark = Theme.of(context).brightness == Brightness.dark;
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: isDark
                ? ColorScheme.dark(primary: Theme.of(context).colorScheme.primary, surface: const Color(0xFF16213E))
                : ColorScheme.light(primary: Theme.of(context).colorScheme.primary),
          ),
          child: child!,
        );
      },
    );

    if (range != null) {
      setState(() {
        _startDate = range.start;
        _endDate = range.end;
      });
    }
  }

  void _save() {
    if (!_formKey.currentState!.validate()) return;
    if (_startDate == null || _endDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select dates'), backgroundColor: Colors.orange));
      return;
    }

    final savedTripData = widget.onSave(_titleCtrl.text.trim(), _destCtrl.text.trim(), _startDate!, _endDate!, _descCtrl.text.trim());
    Navigator.pop(context, savedTripData);
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primary = Theme.of(context).colorScheme.primary;
    final keyboardHeight = MediaQuery.of(context).viewInsets.bottom;
    final isEditing = widget.existingTrip != null;
    final dateFormat = DateFormat('MMM d, yyyy');

    return Container(
      margin: EdgeInsets.only(top: 80, bottom: keyboardHeight),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF16213E) : Colors.white,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(width: 40, height: 4, decoration: BoxDecoration(color: Colors.grey[400], borderRadius: BorderRadius.circular(2))),
              const SizedBox(height: 24),
              Text(isEditing ? 'Edit Trip' : 'Create New Trip', style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold, color: isDark ? Colors.white : Colors.black87)),
              const SizedBox(height: 24),

              // Inputs
              _Input(ctrl: _titleCtrl, label: 'Trip Title', icon: Icons.map, isDark: isDark, validator: (v) => v!.isEmpty ? 'Required' : null),
              const SizedBox(height: 16),
              _Input(ctrl: _destCtrl, label: 'Destination', icon: Icons.location_city, isDark: isDark, validator: (v) => v!.isEmpty ? 'Required' : null),
              const SizedBox(height: 16),
              
              // Date picker
              InkWell(
                onTap: _pickDateRange,
                borderRadius: BorderRadius.circular(16),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                  decoration: BoxDecoration(
                    color: isDark ? const Color(0xFF0D1B2A) : Colors.grey[50],
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: isDark ? Colors.grey[700]! : Colors.grey[300]!),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.calendar_month, color: isDark ? Colors.white38 : Colors.grey[500], size: 20),
                      const SizedBox(width: 16),
                      Text(
                        _startDate != null && _endDate != null
                            ? '${dateFormat.format(_startDate!)} - ${dateFormat.format(_endDate!)}'
                            : 'Select Dates',
                        style: GoogleFonts.poppins(color: _startDate != null ? (isDark ? Colors.white : Colors.black87) : (isDark ? Colors.white54 : Colors.grey[600]), fontSize: 14),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),
              _Input(ctrl: _descCtrl, label: 'Description (Optional)', icon: Icons.notes, isDark: isDark, maxLines: 3),
              const SizedBox(height: 32),

              SizedBox(
                width: double.infinity,
                height: 52,
                child: FilledButton(
                  onPressed: _save,
                  style: FilledButton.styleFrom(backgroundColor: primary, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))),
                  child: Text('Save Trip', style: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _Input extends StatelessWidget {
  final TextEditingController ctrl;
  final String label;
  final IconData icon;
  final bool isDark;
  final String? Function(String?)? validator;
  final int maxLines;

  const _Input({required this.ctrl, required this.label, required this.icon, required this.isDark, this.validator, this.maxLines = 1});

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: ctrl,
      validator: validator,
      maxLines: maxLines,
      style: GoogleFonts.poppins(color: isDark ? Colors.white : Colors.black87, fontSize: 14),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: GoogleFonts.poppins(color: isDark ? Colors.white54 : Colors.grey[600], fontSize: 13),
        prefixIcon: Icon(icon, color: isDark ? Colors.white38 : Colors.grey[500], size: 20),
        filled: true,
        fillColor: isDark ? const Color(0xFF0D1B2A) : Colors.grey[50],
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: isDark ? Colors.grey[700]! : Colors.grey[300]!)),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: isDark ? Colors.grey[700]! : Colors.grey[300]!)),
        contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: maxLines > 1 ? 16 : 0),
      ),
    );
  }
}
